services:
  latex:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - fontcache:/usr/local/texlive/2023/texmf-var/lualatex-cache
      - ../:/home/
    stdin_open: true
    tty: true

volumes:
  fontcache:
