services:
  latex:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - fontcache:/usr/local/texlive/2022/texmf-var/lualatex-cache
      - ../src:/home/src
    stdin_open: true
    tty: true

volumes:
  fontcache: