name: Docker Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build with Docker
      run: |
        docker compose -f ./.devcontainer/docker-compose.yml build
        docker compose -f ./.devcontainer/docker-compose.yml up -d
        docker exec -it $(docker ps -q --filter name=latex) sh -c "cd /home/src && llmk"
        docker cp $(docker ps -q --filter name=latex):/home/src/main.pdf ./main.pdf
    - name: Set tag name from ref
      id: set_tag
      run: echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: ./main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
