name: Docker Build and Release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Specify the tag to build and release'
        required: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.inputs.tag }}

    - name: Build with Docker
      run: |
        mkdir output
        docker compose -f ./.devcontainer/docker-compose.yml build
        docker compose -f ./.devcontainer/docker-compose.yml up -d
        docker exec $(docker ps -q --filter name=latex) sh -c "cd /home/src && llmk"
        docker cp $(docker ps -q --filter name=latex):/home/src/main.pdf ./output/main.pdf
    - name: Set tag name from ref
      id: set_tag
      run: |
        if [ -n "${{ github.event.inputs.tag }}" ]; then
          echo "Using tag from manual inputs"
          echo ::set-output name=TAG_NAME::${{ github.event.inputs.tag }}
        else
          echo "Using tag from push event"
          echo ::set-output name=TAG_NAME::${GITHUB_REF#refs/tags/}
        fi

    - name: Upload release asset
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./output/main.pdf
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TAG_NAME: ${{ steps.set_tag_outputs.TAG_NAME }}
